service: event-handler # NOTE: update this with your service name
app: aes-events-telegram-chat-bot

plugins:
  - serverless-plugin-include-dependencies

provider:
  name: aws
  runtime: nodejs12.x
  stage: default
  region: us-east-1
  memorySize: 512
  timeout: 10

package:
  include:
    - dist/**
  exclude:
    - node_modules/**
    - src/**
    - .editorconfig
    - .eslintignore
    - .eslintrc.json
    - .gitignore
    - .prettierignore
    - .prettierrc
    - deploy.sh

functions:
  eventsHandler:
    handler: dist/index.handler

    events:
      - http:
          path: /
          method: get
